[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gazequestionnaire"
version = "1.3"
requires-python = ">=3.10"

[project.scripts]
gq-run = "main:cli"

[tool.setuptools]
packages = { find = { where = ["."] } }
py-modules = ["main"]
